config/routes.rb
Rails.application.routes.draw do

  root 'team_comps#index'
  get '/team_comps/search', to: 'team_comps#search', as: 'search'
  resources :team_comps do
    resources :comments, only: [:create, :destroy] do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    member do
      put "like", to: "team_comps#upvote"
      put "dislike", to: "team_comps#downvote"
    end
  end

  resources :heroes, only: [:index, :show]

  resources :users, except: [:index] do
    member do
      get :activate
    end
  end
  resources :password_resets, only: [:create, :edit, :update]
  get '/users/:id/resend_activation', to: 'users#resend_activation', as: 'resend_activation'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/about', to: 'sessions#about', as: 'about'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    render :create
  end

  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      render :update
    else
      render :action => "edit"
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/create.html.erb
<h1>Password Reset Email Sent</h1>

<p>If there is a user with that email address, We have sent them an email
  with a link to reset their password. If you haven't recieved it yet,
  please be sure to check your junk/spam folder.</p>

app/views/password_resets/edit.html.erb
<h1>Choose a New Password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if f.object.errors.any? %>
  <div class="errors" id="errors">
    <% if f.object.errors.any? %>
      <ul>
        <% f.object.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= submit_tag nil, class: "btn btn-default" %>
  </div>
<% end %>

app/views/password_resets/update.html.erb
<h1>Password Changed</h1>

<p>You have successfully changed your password.<p>

<p><%= link_to "Click Here", login_path %> to log in.</p>