config/routes.rb
Rails.application.routes.draw do

  root 'team_comps#index'
  get '/team_comps/search', to: 'team_comps#search', as: 'search'
  resources :team_comps do
    resources :comments, only: [:create, :destroy] do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    member do
      put "like", to: "team_comps#upvote"
      put "dislike", to: "team_comps#downvote"
    end
  end

  resources :heroes, only: [:index, :show]

  resources :users, except: [:index] do
    member do
      get :activate
    end
  end
  resources :password_resets, only: [:create, :edit, :update]
  get '/users/:id/resend_activation', to: 'users#resend_activation', as: 'resend_activation'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/about', to: 'sessions#about', as: 'about'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :username, uniqueness: true, format: {with: /\w{6,}/}

  has_many :comments, foreign_key: "author_id"
  has_many :team_comps, foreign_key: "author_id"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :activate]

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      render :activate
    else
      not_authenticated
    end
  end

  def new
    redirect_to(current_user) if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render :create
    else
      render :new
    end
  end

  def resend_activation
    @user = User.find(params[:id])
    UserMailer.activation_needed_email(@user).deliver
    render :create
  end

  def show
    @user = User.find(params[:id])
    @team_comps = Kaminari.paginate_array(sorted_comps("Rating: High-Low")).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.valid_password?(params[:old_password]) && @user.update_attributes(user_params)
      redirect_to @user, notice: "User successfully updated."
    else
      render :edit
    end
  end

  # These will be added when changing emails is implemented

  # def edit_password
  #   @user = User.find(params[:id])
  #   if @user == current_user
  #     render :edit_password
  #   else
  #     redirect_to edit_user_path(current_user)
  #   end
  # end
  #
  # def update_password
  #   @user = User.find(params[:id])
  #
  #   if @user.update_attributes(user_params)
  #     redirect_to @user, notice: "User successfully updated."
  #   else
  #     render :edit_password
  #   end
  # end

  def destroy
  end

  private

  def user_params
  params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def sorted_comps(sort_method)
    sort_options = {
      "Rating: High-Low" => [:score, :updated_integer, true],
      "Rating: Low-High" => [:neg_score, :updated_integer, true],
      "Name: A-Z" => [:name, :neg_updated_integer, false],
      "Name: Z-A" => [:name, :neg_updated_integer, true],
      "Updated: Newest first" => [:updated_integer, :score, true],
      "Updated: Oldest first" => [:updated_integer, :neg_score, false]}
    comps = TeamComp.where(author_id: @user.id).sort_by {|comp| [0,1].map {|i| comp.send(sort_options[sort_method][i])}}
    comps.reverse! if sort_options[sort_method][2]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comp_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Objective</th>
      <th>Lineup</th>
      <th>Rating</th>
      <th>Strategy</th>
    </tr>
  </thead>
  <tbody>
    <% @team_comps.each do |comp| %>
      <tr>
        <td><%= link_to comp.name, comp %></td>
        <td><%= comp.objective %></td>
        <td>
          <%= link_to(image_tag(comp.hero1.icon_path, size: "35x35"), comp.hero1) %>
          <%= link_to(image_tag(comp.hero2.icon_path, size: "35x35"), comp.hero2) %>
          <%= link_to(image_tag(comp.hero3.icon_path, size: "35x35"), comp.hero3) %>
          <%= link_to(image_tag(comp.hero4.icon_path, size: "35x35"), comp.hero4) %>
          <%= link_to(image_tag(comp.hero5.icon_path, size: "35x35"), comp.hero5) %>
          <%= link_to(image_tag(comp.hero6.icon_path, size: "35x35"), comp.hero6) %>
        </td>
        <td>
          <%= comp.score %>
        </td>
        <td><%= comp.strategy.truncate(50) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
<%= paginate @team_comps %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if f.object.errors.any? %>
  <div class="errors" id="errors">
    <% if f.object.errors.any? %>
      <ul>
        <% f.object.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% end %>
  <div class="input-field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div><br>
  <div class="input-field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div><br>
  <div class="input-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div><br>
  <div class="input-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div>
    <%= submit_tag nil, class: "btn btn-default" %>
  </div>

  <% end %>

app/views/users/_password_change.html.erb
<%= form_for @user do |f| %>
  <% if f.object.errors.any? %>
  <div class="errors" id="errors">
    <% if f.object.errors.any? %>
      <ul>
        <% f.object.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% end %>
  <div class="input-field">
    <%= label_tag :old_password, "Current Password" %>
    <%= password_field_tag :old_password %>
  </div><br>
  <div class="input-field">
    <%= f.label :password, "New Password" %>
    <%= f.password_field :password %>
  </div><br>
  <div class="input-field">
    <%= f.label :password_confirmation, "Confirm New Password" %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div>
    <%= submit_tag nil, class: "btn btn-default" %>
  </div>

<% end %>

app/views/users/activate.html.erb
<h1>User Activated</h1>

<p>You have successfully activated your account.<p>

<p><%= link_to "Click Here", login_path %> to log in.</p>

app/views/users/create.html.erb
<h1>User Created Successfully</h1>

<p>You have successfully created an account.<br>
A confirmation email has been sent to <%= @user.email %>, and should arrive shortly.<br>
If you have not recieved it, please check your junk/spam folder. Otherwise,
<%= link_to 'click here to re-send', resend_activation_path(@user) %>.

app/views/users/edit.html.erb
<h1>Edit Password for <%= @user.username %></h1>

<%= render 'password_change' %>

app/views/users/edit_email.html.erb
<!-- This page is not yet implemented -->
<h1>Edit Email for <%= @user.username %></h1>

<%= form_for @user do |f| %>
  <% if f.object.errors.any? %>
    <div class="errors" id="errors">
      <% if f.object.errors.any? %>
        <ul>
          <% f.object.errors.full_messages.each do |e| %>
            <li><%= e %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
  <div class="input-field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div><br>
  <div>
    <%= submit_tag nil, class: "btn btn-default btn-xs" %>
  </div>

<% end %>

app/views/users/edit_password.html.erb
<h1>Verify Password</h1>

<%= form_for @user do |f| %>
  <% if f.object.errors.any? %>
  <div class="errors" id="errors">
    <% if f.object.errors.any? %>
      <ul>
        <% f.object.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% end %>
  <div class="input-field">
    <%= label_tag :old_password, "Current Password" %>
    <%= text_field_tag :old_password %>
  </div><br>
  <div class="input-field">
    <%= f.label :password, "New Password" %>
    <%= f.password_field :password %>
  </div><br>
  <div class="input-field">
    <%= f.label :password_confirmation, "Confirm New Password" %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div>
    <%= submit_tag, nil, class: "btn btn-default btn-xs" %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User: <%= @user.username %></h1>

<% if @user == current_user %>
<!-- <%= link_to "Change Email", edit_user_path %> - -->
<%= link_to "Edit Password", edit_user_path %>
<% end %>

<% if @team_comps.any? %>
  <h3>Team Comps</h3>

  <%= form_tag @user, :method => 'get' do %>
    <%= label_tag :sort_method, "Sort By" %>
    <% selected = (params[:sort_method] ? params[:sort_method] : "Rating: High-Low") %>
    <%= select_tag :sort_method, options_for_select(["Rating: High-Low", "Rating: Low-High", "Name: A-Z", "Name: Z-A", "Updated: Newest first", "Updated: Oldest first"], selected) %>

    <%= submit_tag "Sort", class: "btn btn-default btn-xs" %>
  <% end %>
<p></p>

  <%= render 'comp_table' %>
<% end %>