config/routes.rb
Rails.application.routes.draw do

  root 'team_comps#index'
  get '/team_comps/search', to: 'team_comps#search', as: 'search'
  resources :team_comps do
    resources :comments, only: [:create, :destroy] do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    member do
      put "like", to: "team_comps#upvote"
      put "dislike", to: "team_comps#downvote"
    end
  end

  resources :heroes, only: [:index, :show]

  resources :users, except: [:index] do
    member do
      get :activate
    end
  end
  resources :password_resets, only: [:create, :edit, :update]
  get '/users/:id/resend_activation', to: 'users#resend_activation', as: 'resend_activation'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/about', to: 'sessions#about', as: 'about'

end

app/models/team_comp.rb
class TeamComp < ActiveRecord::Base
  include PgSearch
  acts_as_votable

  validates :name, presence: true
  validates :objective, presence: true
  validates :strategy, presence: true
  validates :author, presence: true
  validate :validate_hero_ids
  after_validation :sort_hero_ids


  has_many :comments
  belongs_to :author, class_name: "User"
  belongs_to :hero1, class_name: "Hero"
  belongs_to :hero2, class_name: "Hero"
  belongs_to :hero3, class_name: "Hero"
  belongs_to :hero4, class_name: "Hero"
  belongs_to :hero5, class_name: "Hero"
  belongs_to :hero6, class_name: "Hero"

  pg_search_scope :search_by_name, :against => :name
  pg_search_scope :search_by_objective, :against => :objective
  pg_search_scope :search_by_strategy, :against => :strategy

  #This is the method that will run whenever a search is being performed where heroes are specified.
  def self.search_heroes(ids)
    comps = all
    #sorts ids into ascending order numerically
    ids.compact!.sort!
    #creates a 2D array, where each element is of the form [hero_id, number of copies of the hero_id, starting point for the search]
    sorted_ids = ids.uniq.map { |hero_id| [hero_id, ids.count(hero_id), ids.index(hero_id)] }
    #gradually filters comps using the self.search_hero method, doing so once for every unique hero_id given.
    sorted_ids.each { |sorted_id| comps = comps.select {|comp| search_hero(comps, sorted_id, ids.length).include?(comp)} }
    comps
  end

  #This is the method that self.search_heroes uses on each hero_id to pick out valid team comps.
  def self.search_hero(comps, sorted_id, length)
    sorted_comps = []
    #Starts at the first hero_id column that the sorted_id could show up in, and goes until the last possible one.
    (sorted_id[2] + 1).step(by: 1, to: (7 - (length - sorted_id[2]) ) ) do |i|
      sort_cluster = comps
      #Filters sort_cluster once for every instance of a given hero, selecting only the team_comps where the hero shows up the given number of times.
      sorted_id[1].times do |n|
        sort_cluster = sort_cluster.select{|comp| comp.send(:"hero#{i+n}_id") == sorted_id[0]}
      end
      #Adds the cluster generated by the above line to sorted_comps.
      sorted_comps += sort_cluster
    end
    sorted_comps.uniq
  end


  def sort_hero_ids
    unless hero_ids.any?{|hero_id| hero_id == nil}
      heroes = hero_ids.sort
      1.step(by: 1, to: 6){|i| send(:"hero#{i.to_s}_id=", heroes[i-1])}
    end
  end

  def hero_ids
    hero_ids = []
    1.step(by: 1, to: 6){|i| hero_ids.push(send(:"hero#{i.to_s}_id"))}
    hero_ids
  end

  def validate_hero_ids
    errors.add(:heroes, "can't be blank.") if hero_ids.any?{|hero_id| hero_id == nil}
  end

  def score
    get_upvotes.size - get_downvotes.size
  end

  def neg_score
    0-score
  end

  def updated_integer
    updated_at.to_i
  end

  def neg_updated_integer
    0-updated_integer
  end

end

app/controllers/team_comps_controller.rb
class TeamCompsController < ApplicationController
  def index
    comps = (params[:sort_method] ? sort_comps(params[:sort_method]) : sort_comps("Rating: High-Low"))
    @team_comps = comps
  end

  def search
    comps = (params[:name] ? search_results : TeamComp.all)
    sort_method = (params[:sort_method] ? params[:sort_method] : "Rating: High-Low")
    @team_comps = sort_comps(sort_method, comps)
  end

  def show
    @team_comp = TeamComp.find(params[:id])
    comments = (params[:sort_method] ? sort_comments(params[:sort_method], @team_comp) : sort_comments("Rating: High-Low", @team_comp))
    @comments = Kaminari.paginate_array(comments).page(params[:page])
    @comment = Comment.new(author_id: current_user.id, team_comp_id: params[:id]) if current_user
  end

  def new
    @offense = Hero.where(role: "Offense")
    @defense = Hero.where(role: "Defense")
    @tank = Hero.where(role: "Tank")
    @support = Hero.where(role: "Support")
    @team_comp = TeamComp.new(author_id: current_user.id)
  end

  def create
    @team_comp = TeamComp.new(team_comp_params)
    @team_comp.author_id = current_user.id

    if @team_comp.save
      redirect_to @team_comp, notice: "Team Comp successfully created."
    else
      render :new
    end
  end

  def edit
    @team_comp = TeamComp.find(params[:id])
  end

  def update
    @team_comp = TeamComp.find(params[:id])

    if @team_comp.update_attributes(team_comp_params)
      redirect_to @team_comp, notice: "Team Comp successfully updated."
    else
      render :edit
    end
  end

  def upvote
    @team_comp = TeamComp.find(params[:id])
    @team_comp.upvote_by current_user
    redirect_to(:back)
  end

  def downvote
    @team_comp = TeamComp.find(params[:id])
    @team_comp.downvote_by current_user
    redirect_to(:back)
  end

  def destroy
    @team_comp = TeamComp.find(params[:id])
    @team_comp.destroy
    redirect_to :team_comps, notice: "Team Comp successfully destroyed."
  end

  private

  def team_comp_params
    params.require(:team_comp).permit(:name, :author_id, :objective, :hero1_id,
      :hero2_id, :hero3_id, :hero4_id, :hero5_id, :hero6_id, :strategy)
  end

  def search_results
    comps = TeamComp.all
    heroes = [params[:hero1_id], params[:hero2_id], params[:hero3_id], params[:hero4_id], params[:hero5_id], params[:hero6_id]].map do |h_id|
      h_id == "" ? nil : h_id.to_i
    end
    comps = comps.search_by_name(params[:name]) if params[:name] != ""
    comps = comps.search_by_objective(params[:objective]) if params[:objective] != ""
    comps = comps.search_by_strategy(params[:strategy]) if params[:strategy] != ""
    comps = comps.search_heroes(heroes) if heroes.any?
  end

  def sort_comps(sort_method, comps = TeamComp.all)
    sort_options = {
      "Rating: High-Low" => [:score, :updated_integer, true],
      "Rating: Low-High" => [:neg_score, :updated_integer, true],
      "Name: A-Z" => [:name, :neg_updated_integer, false],
      "Name: Z-A" => [:name, :neg_updated_integer, true],
      "Updated: Newest first" => [:updated_integer, :score, true],
      "Updated: Oldest first" => [:updated_integer, :neg_score, false]}
    sorted_comps = comps.sort_by {|comp| [0,1].map {|i| comp.send(sort_options[sort_method][i])}}
    sorted_comps.reverse! if sort_options[sort_method][2]
    Kaminari.paginate_array(sorted_comps).page(params[:page])
  end

  def sort_comments(sort_method, comp)
    sort_options = {
      "Rating: High-Low" => [:score, :updated_integer, true],
      "Rating: Low-High" => [:neg_score, :updated_integer, true],
      "Name: A-Z" => [:name, :neg_updated_integer, false],
      "Name: Z-A" => [:name, :neg_updated_integer, true],
      "Updated: Newest first" => [:updated_integer, :score, true],
      "Updated: Oldest first" => [:updated_integer, :neg_score, false]}
    comments = comp.comments.sort_by {|comment| [0,1].map {|i| comment.send(sort_options[sort_method][i])}}
    comments.reverse! if sort_options[sort_method][2]
  end
end

app/helpers/team_comps_helper.rb
module TeamCompsHelper

  def objective_options
    ["Assault, Attack", "Assault, Defend", "Escort, Attack", "Escort, Defend", "Hybrid, Attack", "Hybrid, Defend", "Control"].map do |objective|
        [objective, objective]
    end
  end

  def hero_options
    Hero.all.map do |hero|
      [hero.name, hero.id]
    end
  end
end

app/views/team_comps/_comments.html.erb
<% @comments.each do |comment| %>
  <p>
    <%= link_to "^", like_team_comp_comment_path(@team_comp.id, comment), method: 'put', class: "upvote" %>
    <%= comment.score %>
    <%= link_to "v", dislike_team_comp_comment_path(@team_comp.id, comment), method: 'put', class: "downvote" %>
    <b><%= link_to(comment.author.username, comment.author) %>:</b>
  <%= comment.content %></p>
<% end %>

<div>
<%= paginate @comments %>
</div>

app/views/team_comps/_comp_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Objective</th>
      <th>Lineup</th>
      <th>Rating</th>
      <th>Author</th>
      <th>Strategy</th>
    </tr>
  </thead>
  <tbody>
    <% @team_comps.each do |comp| %>
      <tr>
        <td><%= link_to comp.name, comp %></td>
        <td><%= comp.objective %></td>
        <td>
          <%= link_to(image_tag(comp.hero1.icon_path, size: "35x35"), comp.hero1) %>
          <%= link_to(image_tag(comp.hero2.icon_path, size: "35x35"), comp.hero2) %>
          <%= link_to(image_tag(comp.hero3.icon_path, size: "35x35"), comp.hero3) %>
          <%= link_to(image_tag(comp.hero4.icon_path, size: "35x35"), comp.hero4) %>
          <%= link_to(image_tag(comp.hero5.icon_path, size: "35x35"), comp.hero5) %>
          <%= link_to(image_tag(comp.hero6.icon_path, size: "35x35"), comp.hero6) %>
        </td>
        <td>
          <%= link_to "^", like_team_comp_path(comp), method: 'put', class: "upvote" %>
          <%= comp.score %>
          <%= link_to "v", dislike_team_comp_path(comp), method: 'put', class: "downvote" %>
        </td>
        <td><%= link_to comp.author.username, comp.author %></td>
        <td><%= comp.strategy.truncate(50) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
<%= paginate @team_comps %>
</div>

app/views/team_comps/_form.html.erb
<%= form_for @team_comp do |f| %>
<% if f.object.errors.any? %>
<div class="errors" id="errors">
  <% if f.object.errors.any? %>
    <ul>
      <% f.object.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<% end %>


<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :objective %>
  <%= f.select :objective, objective_options, include_blank: true %>
</div>

<div><p></p></div>

<div>
  <%= f.label :hero1_id, "Hero 1" %>
  <%= f.select :hero1_id, hero_options, include_blank: true %>
</div>

<div>
  <%= f.label :hero2_id, "Hero 2" %>
  <%= f.select :hero2_id, hero_options, include_blank: true %>
</div>

<div>
  <%= f.label :hero3_id, "Hero 3" %>
  <%= f.select :hero3_id, hero_options, include_blank: true %>
</div>

<div>
  <%= f.label :hero4_id, "Hero 4" %>
  <%= f.select :hero4_id, hero_options, include_blank: true %>
</div>

<div>
  <%= f.label :hero5_id, "Hero 5" %>
  <%= f.select :hero5_id, hero_options, include_blank: true %>
</div>

<div>
  <%= f.label :hero6_id, "Hero 6" %>
  <%= f.select :hero6_id, hero_options, include_blank: true %>
</div>

<div>
  <%= f.label :strategy %><br>
  <%= f.text_area :strategy, size: "50x4" %>
</div>

<div>
  <%= submit_tag nil, class: "btn btn-default" %>
</div>

<% end %>

app/views/team_comps/edit.html.erb
<h1>Edit Team Comp</h1>

<%= render 'form' %>

app/views/team_comps/index.html.erb
<h1>Team Comps</h1>

<div class="row">
  <div class="col-sm-3">
    <%= form_tag search_path, :method => 'get' do %>
      <%= text_field_tag :name, params[:name], placeholder: 'Search by Comp Name' %>
      <%= submit_tag "Search", class: "btn btn-default btn-xs" %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <h4><%= link_to "Advanced Search", search_path %></h4>
  </div>
</div>

<% if current_user %>
  <div class="row">
    <div class="col-sm-12"></div>
    <div class="col-sm-3">
      <h3><%= link_to "New Comp", new_team_comp_path %></h3>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="cols-sm-12"></div>
    <div class="col-sm-3">
      <h3>New Around here? <%= link_to "Sign up here", new_user_path %> to start creating team comps!</h3>
    </div>
  </div>
<% end %>

<div class="row">
  <% if @team_comps.count > 20 %>
    <div class="col-sm-3">
      <%= paginate @team_comps %>
    </div>
  <% end %>
  <div class="col-sm-3">
    <%= form_tag team_comps_path, :method => 'get' do %>
      <%= label_tag :sort_method, "Sort By" %>
      <% selected = (params[:sort_method] ? params[:sort_method] : "Rating: High-Low") %>
      <%= select_tag :sort_method, options_for_select(["Rating: High-Low", "Rating: Low-High", "Name: A-Z", "Name: Z-A", "Updated: Newest first", "Updated: Oldest first"], selected) %>

      <%= submit_tag "Sort", class: "btn btn-default btn-xs" %>
    <% end %>
  </div>
</div>

<%= render 'comp_table' %>

app/views/team_comps/new.html.erb
<h1>New Team Comp</h1>

<%= render 'form' %>

app/views/team_comps/search.html.erb
<h1>Advanced Search</h1>

<%= form_tag search_path, method: 'get' do %>

<div>
  <%= label_tag :name, "Name" %>
  <%= text_field_tag :name, params[:name] %>
</div>

<div><p></p></div>
<div>
  <%= label_tag :objective %>
  <%= select_tag :objective, options_for_select(objective_options, params[:objective]), include_blank: true %>
</div>

<div><p></p></div>

<div>
  <%= label_tag :hero1_id, "Hero 1" %>
  <%= select_tag :hero1_id, options_for_select(hero_options, params[:hero1_id]), include_blank: true %>
</div>

<div>
  <%= label_tag :hero2_id, "Hero 2" %>
  <%= select_tag :hero2_id, options_for_select(hero_options, params[:hero2_id]), include_blank: true %>
</div>

<div>
  <%= label_tag :hero3_id, "Hero 3" %>
  <%= select_tag :hero3_id, options_for_select(hero_options, params[:hero3_id]), include_blank: true %>
</div>

<div>
  <%= label_tag :hero4_id, "Hero 4" %>
  <%= select_tag :hero4_id, options_for_select(hero_options, params[:hero4_id]), include_blank: true %>
</div>

<div>
  <%= label_tag :hero5_id, "Hero 5" %>
  <%= select_tag :hero5_id, options_for_select(hero_options, params[:hero5_id]), include_blank: true %>
</div>

<div>
  <%= label_tag :hero6_id, "Hero 6" %>
  <%= select_tag :hero6_id, options_for_select(hero_options, params[:hero6_id]), include_blank: true %>
</div>

<div>
  <br><%= label_tag :strategy %><br>
  <%= text_area_tag :strategy, params[:strategy], size: "50x4" %>
</div>

<div>
  <%= label_tag :sort_method, "Sort By" %>
  <% selected = (params[:sort_method] ? params[:sort_method] : "Rating: High-Low") %>
  <%= select_tag :sort_method, options_for_select(["Rating: High-Low", "Rating: Low-High", "Name: A-Z", "Name: Z-A", "Updated: Newest first", "Updated: Oldest first"], selected) %>
</div>

<div>
  <br><%= submit_tag "Search", class: "btn btn-default" %>
</div>
<% end %>

<h2>Results</h2>
<% if @team_comps.any? %>

  <%= paginate @team_comps %>

  <%= render 'comp_table' %>

<% else %>

  No matching team comps were found.

<% end %>

app/views/team_comps/show.html.erb
<h1><%= @team_comp.name %></h1>

  <% if @team_comp.author == current_user %>
    <p><%= link_to "Edit", edit_team_comp_path %></p>
  <% end %>

  <b>Author:</b> <%= link_to @team_comp.author.username, @team_comp.author %><br><br>
  <b>Objective:</b> <%= @team_comp.objective %><br><br>
  <b>Rating:</b>
    <%= link_to "^", like_team_comp_path(@team_comp), method: 'put', class: "upvote" %>
    <%= @team_comp.score %>
    <%= link_to "v", dislike_team_comp_path(@team_comp), method: 'put', class: "downvote" %><br>


<h3>Heroes</h3>

<div class="row">

  <div class="col-sm-1 text-center">
    <div class="row">
      <%= link_to(image_tag(@team_comp.hero1.icon_path, size: "80x80"), @team_comp.hero1) %>
    </div>
    <div class="row">
      <%= link_to @team_comp.hero1.name, @team_comp.hero1 %>
    </div>
    <div class="row">
      <%= image_tag "role-icons/#{@team_comp.hero1.role.downcase}-icon.png", size: "30x30" %>
    </div>
  </div>
  <div class="col-sm-1 text-center">
    <div class="row">
      <%= link_to(image_tag(@team_comp.hero2.icon_path, size: "80x80"), @team_comp.hero2) %>
    </div>
    <div class="row">
      <%= link_to @team_comp.hero2.name, @team_comp.hero2 %>
    </div>
    <div class="row">
      <%= image_tag "role-icons/#{@team_comp.hero2.role.downcase}-icon.png", size: "30x30" %>
    </div>
  </div>
  <div class="col-sm-1 text-center">
    <div class="row">
      <%= link_to(image_tag(@team_comp.hero3.icon_path, size: "80x80"), @team_comp.hero3) %>
    </div>
    <div class="row">
      <%= link_to @team_comp.hero3.name, @team_comp.hero3 %>
    </div>
    <div class="row">
      <%= image_tag "role-icons/#{@team_comp.hero3.role.downcase}-icon.png", size: "30x30" %>
    </div>
  </div>
  <div class="col-sm-1 text-center">
    <div class="row">
      <%= link_to(image_tag(@team_comp.hero4.icon_path, size: "80x80"), @team_comp.hero4) %>
    </div>
    <div class="row">
      <%= link_to @team_comp.hero4.name, @team_comp.hero4 %>
    </div>
    <div class="row">
      <%= image_tag "role-icons/#{@team_comp.hero4.role.downcase}-icon.png", size: "30x30" %>
    </div>
  </div>
  <div class="col-sm-1 text-center">
    <div class="row">
      <%= link_to(image_tag(@team_comp.hero5.icon_path, size: "80x80"), @team_comp.hero5) %>
    </div>
    <div class="row">
      <%= link_to @team_comp.hero5.name, @team_comp.hero5 %>
    </div>
    <div class="row">
      <%= image_tag "role-icons/#{@team_comp.hero5.role.downcase}-icon.png", size: "30x30" %>
    </div>
  </div>
  <div class="col-sm-1 text-center">
    <div class="row">
      <%= link_to(image_tag(@team_comp.hero6.icon_path, size: "80x80"), @team_comp.hero6) %>
    </div>
    <div class="row">
      <%= link_to @team_comp.hero6.name, @team_comp.hero6 %>
    </div>
    <div class="row">
      <%= image_tag "role-icons/#{@team_comp.hero6.role.downcase}-icon.png", size: "30x30" %>
    </div>
  </div>

</div>
<h3>Strategy</h3>
<p><%= @team_comp.strategy %></p>

<h2>Comments</h2>

<% if current_user %>
  <%= form_for [@team_comp, @comment] do |f| %>

  <%= f.label :content, "New Comment" %><br>
  <%= f.text_area :content, size: "50x4" %><br>

  <%= submit_tag nil, class: "btn btn-default" %>

  <% end %>
<% end %>

<% if @comments.any? %>
<p></p>
  <%= form_tag @team_comp, :method => 'get' do %>
    <%= label_tag :sort_method, "Sort By" %>
    <% selected = (params[:sort_method] ? params[:sort_method] : "Rating: High-Low") %>
    <%= select_tag :sort_method, options_for_select(["Rating: High-Low", "Rating: Low-High", "Name: A-Z", "Name: Z-A", "Updated: Newest first", "Updated: Oldest first"], selected) %>

    <%= submit_tag "Sort", class: "btn btn-default btn-xs" %>
  <% end %>
  <p></p>
<% end %>

<%= render 'comments' %>