config/routes.rb
Rails.application.routes.draw do

  root 'team_comps#index'
  get '/team_comps/search', to: 'team_comps#search', as: 'search'
  resources :team_comps do
    resources :comments, only: [:create, :destroy] do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    member do
      put "like", to: "team_comps#upvote"
      put "dislike", to: "team_comps#downvote"
    end
  end

  resources :heroes, only: [:index, :show]

  resources :users, except: [:index] do
    member do
      get :activate
    end
  end
  resources :password_resets, only: [:create, :edit, :update]
  get '/users/:id/resend_activation', to: 'users#resend_activation', as: 'resend_activation'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/about', to: 'sessions#about', as: 'about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag(source = 'favicon.png') %>
  <title>Überwatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="text-right">
    <% if current_user %>
      <p>Logged in as <%= link_to current_user.username, current_user %> -
      <%= link_to "Logout", logout_path %></p>
    <% else %>
      <p>Not logged in. <%= link_to "Log In", login_path %> -
      <%= link_to "Sign Up", new_user_path %></p>
    <% end %>
  </div>

  <%= link_to(image_tag('logoWhite.png', height: "80"), root_path) %>
  <h4>
    <%= link_to "Home", root_path %> -
    <%= link_to "Heroes", heroes_path %> -
    <%= link_to "About", about_path %> -
    <%= link_to "GitHub", 'https://github.com/lateleo/overwatch_team_builder' %> -
    <%= link_to "Back", :back %>
  </h4>

  <%= yield %>

  <div class="row text-center">
    __________________________________________________________________________
  </div>
  <div class="row">
    <div class="col-sm-12 text-center">
      <h4>
        <%= link_to "Home", root_path %> -
        <%= link_to "Heroes", heroes_path %> -
        <%= link_to "About", about_path %> -
        <%= link_to "GitHub", 'https://github.com/lateleo/overwatch_team_builder' %> -
        <%= link_to "Back", :back %>
      </h4>
    </div>
  </div>
  <div class="row text-center">
    <%= image_tag('circle_icon_light.png', height: "150") %>
  </div>
</div>
</body>
</html>